//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.28 at 05:20:21 PM IST 
//


package com.redn.connect.zostrpt01.len;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.redn.connect.zostrpt01.len package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.redn.connect.zostrpt01.len
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZOSTRPT01 }
     * 
     */
    public ZOSTRPT01 createZOSTRPT01() {
        return new ZOSTRPT01();
    }

    /**
     * Create an instance of {@link ZOSTRPT01 .IDOC }
     * 
     */
    public ZOSTRPT01 .IDOC createZOSTRPT01IDOC() {
        return new ZOSTRPT01 .IDOC();
    }

    /**
     * Create an instance of {@link ZOSTRPT01 .IDOC.ZE1EDK34 }
     * 
     */
    public ZOSTRPT01 .IDOC.ZE1EDK34 createZOSTRPT01IDOCZE1EDK34() {
        return new ZOSTRPT01 .IDOC.ZE1EDK34();
    }

    /**
     * Create an instance of {@link ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDP31 }
     * 
     */
    public ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDP31 createZOSTRPT01IDOCZE1EDK34ZE1EDP31() {
        return new ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDP31();
    }

    /**
     * Create an instance of {@link ZOSTRPT01 .IDOC.EDIDC40 }
     * 
     */
    public ZOSTRPT01 .IDOC.EDIDC40 createZOSTRPT01IDOCEDIDC40() {
        return new ZOSTRPT01 .IDOC.EDIDC40();
    }

    /**
     * Create an instance of {@link ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1ADRM1 }
     * 
     */
    public ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1ADRM1 createZOSTRPT01IDOCZE1EDK34ZE1ADRM1() {
        return new ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1ADRM1();
    }

    /**
     * Create an instance of {@link ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDKFT01 }
     * 
     */
    public ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDKFT01 createZOSTRPT01IDOCZE1EDK34ZE1EDKFT01() {
        return new ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDKFT01();
    }

    /**
     * Create an instance of {@link ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDP31 .ZE1EDPFT01 }
     * 
     */
    public ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDP31 .ZE1EDPFT01 createZOSTRPT01IDOCZE1EDK34ZE1EDP31ZE1EDPFT01() {
        return new ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDP31 .ZE1EDPFT01();
    }

    /**
     * Create an instance of {@link ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDP31 .ZE1EDP19 }
     * 
     */
    public ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDP31 .ZE1EDP19 createZOSTRPT01IDOCZE1EDK34ZE1EDP31ZE1EDP19() {
        return new ZOSTRPT01 .IDOC.ZE1EDK34 .ZE1EDP31 .ZE1EDP19();
    }

}
