
use devconnect;

CREATE TABLE `connect_logs` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UTC_CREATED_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  `LOG_TIMESTAMP` varchar(255) DEFAULT NULL,
  `LOG_LEVEL` varchar(20) DEFAULT NULL,
  `NODE_NAME` varchar(255) DEFAULT NULL,
  `SERVICE_NAME` varchar(255) DEFAULT NULL,
  `THREAD_ID` varchar(255) DEFAULT NULL,
  `MESSAGE_ID` varchar(255) DEFAULT NULL,
  `LOG_ELAPSED_TIME` varchar(255) DEFAULT NULL,
  `MESSAGE_SOURCE` varchar(100) DEFAULT NULL,
  `MESSAGE_ACTION` varchar(100) DEFAULT NULL,
  `LOG_CATEGORY` varchar(100) DEFAULT NULL,
  `LOGGER_NAME` varchar(100) DEFAULT NULL,
  `LOG_CODE` varchar(100) DEFAULT NULL,
  `LOG_MESSAGE` mediumtext,
  `ERROR_DETAILS` text,
  `SRC_UID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1545 DEFAULT CHARSET=utf8;
