//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.28 at 04:03:56 PM IST 
//


package com.redn.connect.zasn.len;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.redn.connect.zasn.len package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.redn.connect.zasn.len
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZASNLEN }
     * 
     */
    public ZASNLEN createZASNLEN() {
        return new ZASNLEN();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC }
     * 
     */
    public ZASNLEN.IDOC createZASNLENIDOC() {
        return new ZASNLEN.IDOC();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 createZASNLENIDOCE1EDL20() {
        return new ZASNLEN.IDOC.E1EDL20();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 createZASNLENIDOCE1EDL20E1EDL37() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 createZASNLENIDOCE1EDL20E1EDL37E1EDL44() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDD54 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDD54 createZASNLENIDOCE1EDL20E1EDL37E1EDL44E1EDD54() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDD54();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EPC03 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EPC03 createZASNLENIDOCE1EDL20E1EDL37E1EDL44E1EPC03() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EPC03();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD52 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD52 createZASNLENIDOCE1EDL20E1EDL37E1EDD52() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD52();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD50 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD50 createZASNLENIDOCE1EDL20E1EDL37E1EDD50() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD50();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL49 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL49 createZASNLENIDOCE1EDL20E1EDL37E1EDL49() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL49();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC04 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC04 createZASNLENIDOCE1EDL20E1EDL37E1EPC04() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC04();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC02 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC02 createZASNLENIDOCE1EDL20E1EDL37E1EPC02() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC02();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 createZASNLENIDOCE1EDL20E1EDL24() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL58 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL58 createZASNLENIDOCE1EDL20E1EDL24E1EDL58() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL58();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1TXTH9 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1TXTH9 createZASNLENIDOCE1EDL20E1EDL24E1TXTH9() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1TXTH9();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL41 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL41 createZASNLENIDOCE1EDL20E1EDL24E1EDL41() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL41();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL35 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL35 createZASNLENIDOCE1EDL20E1EDL24E1EDL35() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL35();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EPC01 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EPC01 createZASNLENIDOCE1EDL20E1EDL24E1EPC01() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EPC01();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 createZASNLENIDOCE1EDL20E1EDL24E1EDD10() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH4 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH4 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDDH4() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH4();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH3 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH3 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDDH3() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH3();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD12 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD12 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDD12() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD12();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL26 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL26 createZASNLENIDOCE1EDL20E1EDL24E1EDL26() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL26();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL47 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL47 createZASNLENIDOCE1EDL20E1EDL47() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL47();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL28 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL28 createZASNLENIDOCE1EDL20E1EDL28() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL28();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 createZASNLENIDOCE1EDL20E1EDL28E1EDL30() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL32 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL32 createZASNLENIDOCE1EDL20E1EDL28E1EDL30E1EDL32() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL32();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL33 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL33 createZASNLENIDOCE1EDL20E1EDL33() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL33();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDDH2 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDDH2 createZASNLENIDOCE1EDL20E1EDDH2() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDDH2();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1TXTH8 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1TXTH8 createZASNLENIDOCE1EDL20E1TXTH8() {
        return new ZASNLEN.IDOC.E1EDL20 .E1TXTH8();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDT13 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDT13 createZASNLENIDOCE1EDL20E1EDT13() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDT13();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1TXTH0 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1TXTH0 createZASNLENIDOCE1EDL20E1EDT13E1TXTH0() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1TXTH0();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1EDL40 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1EDL40 createZASNLENIDOCE1EDL20E1EDT13E1EDL40() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1EDL40();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1ADRM1 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1ADRM1 createZASNLENIDOCE1EDL20E1ADRM1() {
        return new ZASNLEN.IDOC.E1EDL20 .E1ADRM1();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL21 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL21 createZASNLENIDOCE1EDL20E1EDL21() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL21();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.EDIDC40 }
     * 
     */
    public ZASNLEN.IDOC.EDIDC40 createZASNLENIDOCEDIDC40() {
        return new ZASNLEN.IDOC.EDIDC40();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1UPSLINK }
     * 
     */
    public ZASNLEN.IDOC.E1UPSLINK createZASNLENIDOCE1UPSLINK() {
        return new ZASNLEN.IDOC.E1UPSLINK();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1BPXIFORCE }
     * 
     */
    public ZASNLEN.IDOC.E1BPXIFORCE createZASNLENIDOCE1BPXIFORCE() {
        return new ZASNLEN.IDOC.E1BPXIFORCE();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .ZE1EDL20 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .ZE1EDL20 createZASNLENIDOCE1EDL20ZE1EDL20() {
        return new ZASNLEN.IDOC.E1EDL20 .ZE1EDL20();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .ZE1EDL24 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .ZE1EDL24 createZASNLENIDOCE1EDL20ZE1EDL24() {
        return new ZASNLEN.IDOC.E1EDL20 .ZE1EDL24();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL20RET2 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL20RET2 createZASNLENIDOCE1EDL20E1EDL20RET2() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL20RET2();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL22 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL22 createZASNLENIDOCE1EDL20E1EDL22() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL22();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL51 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL51 createZASNLENIDOCE1EDL20E1EDL51() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL51();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDD01 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDD01 createZASNLENIDOCE1EDL20E1EDD01() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDD01();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL18 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL18 createZASNLENIDOCE1EDL20E1EDL18() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL18();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL55 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL55 createZASNLENIDOCE1EDL20E1EDL55() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL55();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL54 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL54 createZASNLENIDOCE1EDL20E1EDL54() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL54();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL39 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL39 createZASNLENIDOCE1EDL20E1EDL37E1EDL39() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL39();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL38 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL38 createZASNLENIDOCE1EDL20E1EDL37E1EDL38() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL38();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDL46 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDL46 createZASNLENIDOCE1EDL20E1EDL37E1EDL44E1EDL46() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDL46();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDL57 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDL57 createZASNLENIDOCE1EDL20E1EDL37E1EDL44E1EDL57() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDL57();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDD54 .E1EDD55 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDD54 .E1EDD55 createZASNLENIDOCE1EDL20E1EDL37E1EDL44E1EDD54E1EDD55() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EDD54 .E1EDD55();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EPC03 .E1IDC03 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EPC03 .E1IDC03 createZASNLENIDOCE1EDL20E1EDL37E1EDL44E1EPC03E1IDC03() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL44 .E1EPC03 .E1IDC03();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD52 .E1EDD53 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD52 .E1EDD53 createZASNLENIDOCE1EDL20E1EDL37E1EDD52E1EDD53() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD52 .E1EDD53();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD50 .E1EDD51 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD50 .E1EDD51 createZASNLENIDOCE1EDL20E1EDL37E1EDD50E1EDD51() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDD50 .E1EDD51();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL49 .E1EDL50 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL49 .E1EDL50 createZASNLENIDOCE1EDL20E1EDL37E1EDL49E1EDL50() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EDL49 .E1EDL50();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC04 .E1IDC04 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC04 .E1IDC04 createZASNLENIDOCE1EDL20E1EDL37E1EPC04E1IDC04() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC04 .E1IDC04();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC02 .E1IDC02 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC02 .E1IDC02 createZASNLENIDOCE1EDL20E1EDL37E1EPC02E1IDC02() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL37 .E1EPC02 .E1IDC02();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL56 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL56 createZASNLENIDOCE1EDL20E1EDL24E1EDL56() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL56();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL24RET2 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL24RET2 createZASNLENIDOCE1EDL20E1EDL24E1EDL24RET2() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL24RET2();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL25 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL25 createZASNLENIDOCE1EDL20E1EDL24E1EDL25() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL25();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL52 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL52 createZASNLENIDOCE1EDL20E1EDL24E1EDL52() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL52();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL53 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL53 createZASNLENIDOCE1EDL20E1EDL24E1EDL53() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL53();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD14 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD14 createZASNLENIDOCE1EDL20E1EDL24E1EDD14() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD14();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL19 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL19 createZASNLENIDOCE1EDL20E1EDL24E1EDL19() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL19();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL11 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL11 createZASNLENIDOCE1EDL20E1EDL24E1EDL11() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL11();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL15 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL15 createZASNLENIDOCE1EDL20E1EDL24E1EDL15() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL15();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL43 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL43 createZASNLENIDOCE1EDL20E1EDL24E1EDL43() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL43();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL12 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL12 createZASNLENIDOCE1EDL20E1EDL24E1EDL12() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL12();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL58 .E1EDL59 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL58 .E1EDL59 createZASNLENIDOCE1EDL20E1EDL24E1EDL58E1EDL59() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL58 .E1EDL59();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1TXTH9 .E1TXTP9 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1TXTH9 .E1TXTP9 createZASNLENIDOCE1EDL20E1EDL24E1TXTH9E1TXTP9() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1TXTH9 .E1TXTP9();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL41 .E1EDL42 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL41 .E1EDL42 createZASNLENIDOCE1EDL20E1EDL24E1EDL41E1EDL42() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL41 .E1EDL42();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL35 .E1EDL36 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL35 .E1EDL36 createZASNLENIDOCE1EDL20E1EDL24E1EDL35E1EDL36() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL35 .E1EDL36();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EPC01 .E1IDC01 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EPC01 .E1IDC01 createZASNLENIDOCE1EDL20E1EDL24E1EPC01E1IDC01() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EPC01 .E1IDC01();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD11 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD11 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDD11() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD11();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD15 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD15 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDD15() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD15();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD13 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD13 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDD13() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD13();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD17 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD17 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDD17() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD17();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD18 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD18 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDD18() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD18();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD19 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD19 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDD19() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD19();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD20 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD20 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDD20() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD20();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH4 .E1EDDP4 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH4 .E1EDDP4 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDDH4E1EDDP4() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH4 .E1EDDP4();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH3 .E1EDDP3 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH3 .E1EDDP3 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDDH3E1EDDP3() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDDH3 .E1EDDP3();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD12 .E1EDD16 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD12 .E1EDD16 createZASNLENIDOCE1EDL20E1EDL24E1EDD10E1EDD12E1EDD16() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDD10 .E1EDD12 .E1EDD16();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL26 .E1EDL27 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL26 .E1EDL27 createZASNLENIDOCE1EDL20E1EDL24E1EDL26E1EDL27() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL24 .E1EDL26 .E1EDL27();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL47 .E1EDL48 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL47 .E1EDL48 createZASNLENIDOCE1EDL20E1EDL47E1EDL48() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL47 .E1EDL48();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL29 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL29 createZASNLENIDOCE1EDL20E1EDL28E1EDL29() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL29();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL31 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL31 createZASNLENIDOCE1EDL20E1EDL28E1EDL30E1EDL31() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL31();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL32 .E1EDL45 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL32 .E1EDL45 createZASNLENIDOCE1EDL20E1EDL28E1EDL30E1EDL32E1EDL45() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL32 .E1EDL45();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL32 .E1ADRM3 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL32 .E1ADRM3 createZASNLENIDOCE1EDL20E1EDL28E1EDL30E1EDL32E1ADRM3() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL28 .E1EDL30 .E1EDL32 .E1ADRM3();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL33 .E1EDL34 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL33 .E1EDL34 createZASNLENIDOCE1EDL20E1EDL33E1EDL34() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL33 .E1EDL34();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDDH2 .E1EDDP2 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDDH2 .E1EDDP2 createZASNLENIDOCE1EDL20E1EDDH2E1EDDP2() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDDH2 .E1EDDP2();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1TXTH8 .E1TXTP8 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1TXTH8 .E1TXTP8 createZASNLENIDOCE1EDL20E1TXTH8E1TXTP8() {
        return new ZASNLEN.IDOC.E1EDL20 .E1TXTH8 .E1TXTP8();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1TXTH0 .E1TXTP0 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1TXTH0 .E1TXTP0 createZASNLENIDOCE1EDL20E1EDT13E1TXTH0E1TXTP0() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1TXTH0 .E1TXTP0();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1EDL40 .E1ADRM2 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1EDL40 .E1ADRM2 createZASNLENIDOCE1EDL20E1EDT13E1EDL40E1ADRM2() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDT13 .E1EDL40 .E1ADRM2();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1ADRM1 .E1ADRE1 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1ADRM1 .E1ADRE1 createZASNLENIDOCE1EDL20E1ADRM1E1ADRE1() {
        return new ZASNLEN.IDOC.E1EDL20 .E1ADRM1 .E1ADRE1();
    }

    /**
     * Create an instance of {@link ZASNLEN.IDOC.E1EDL20 .E1EDL21 .E1EDL23 }
     * 
     */
    public ZASNLEN.IDOC.E1EDL20 .E1EDL21 .E1EDL23 createZASNLENIDOCE1EDL20E1EDL21E1EDL23() {
        return new ZASNLEN.IDOC.E1EDL20 .E1EDL21 .E1EDL23();
    }

}
