//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 02:38:11 PM IST 
//


package com.redn.connect.vo;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConnectEnterpriseMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectEnterpriseMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EnterpriseHeader" type="{http://schemas.connect.com/enterprise/services/2014/05}EnterpriseHeader"/>
 *         &lt;element name="EnterpriseBody" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any processContents='skip'/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectEnterpriseMessage", propOrder = {
    "enterpriseHeader",
    "enterpriseBody"
})
@XmlRootElement(name="ConnectEnterpriseMessage", namespace="http://schemas.connect.com/enterprise/services/2014/05")
@XmlSeeAlso({CustomProps.class})
public class ConnectEnterpriseMessage implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 8764378239648915513L;
	@XmlElement(name = "EnterpriseHeader", required = true)
    protected EnterpriseHeader enterpriseHeader;
    @XmlElement(name = "EnterpriseBody")
    protected ConnectEnterpriseMessage.EnterpriseBody enterpriseBody;

    /**
     * Gets the value of the enterpriseHeader property.
     * 
     * @return
     *     possible object is
     *     {@link EnterpriseHeader }
     *     
     */
    public EnterpriseHeader getEnterpriseHeader() {
        return enterpriseHeader;
    }

    /**
     * Sets the value of the enterpriseHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnterpriseHeader }
     *     
     */
    public void setEnterpriseHeader(EnterpriseHeader value) {
        this.enterpriseHeader = value;
    }

    /**
     * Gets the value of the enterpriseBody property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectEnterpriseMessage.EnterpriseBody }
     *     
     */
    public ConnectEnterpriseMessage.EnterpriseBody getEnterpriseBody() {
        return enterpriseBody;
    }

    /**
     * Sets the value of the enterpriseBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectEnterpriseMessage.EnterpriseBody }
     *     
     */
    public void setEnterpriseBody(ConnectEnterpriseMessage.EnterpriseBody value) {
        this.enterpriseBody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any processContents='skip'/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class EnterpriseBody implements Serializable{

        /**
		 * 
		 */
		private static final long serialVersionUID = 7734733959530374862L;
		@XmlAnyElement
        protected Object any;

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }

    }

}
