//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 02:38:11 PM IST 
//


package com.redn.connect.vo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.redn.connect.vo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EnterpriseHeader_QNAME = new QName("http://schemas.connect.com/enterprise/services/2014/05", "EnterpriseHeader");
    private final static QName _ConnectEnterpriseResponse_QNAME = new QName("http://schemas.connect.com/enterprise/services/2014/05", "ConnectEnterpriseResponse");
    private final static QName _ConnectEnterpriseMessage_QNAME = new QName("http://schemas.connect.com/enterprise/services/2014/05", "ConnectEnterpriseMessage");
    private final static QName _ConnectEnterpriseException_QNAME = new QName("http://schemas.connect.com/enterprise/services/2016/11", "ConnectEnterpriseException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.redn.connect.vo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link ConnectEnterpriseResponse }
     * 
     */
    public ConnectEnterpriseResponse createConnectEnterpriseResponse() {
        return new ConnectEnterpriseResponse();
    }

    /**
     * Create an instance of {@link ConnectEnterpriseMessage }
     * 
     */
    public ConnectEnterpriseMessage createConnectEnterpriseMessage() {
        return new ConnectEnterpriseMessage();
    }

    /**
     * Create an instance of {@link EnterpriseHeader }
     * 
     */
    public EnterpriseHeader createEnterpriseHeader() {
        return new EnterpriseHeader();
    }

    /**
     * Create an instance of {@link ConnectEnterpriseException }
     * 
     */
    public ConnectEnterpriseException createConnectEnterpriseException() {
        return new ConnectEnterpriseException();
    }

    /**
     * Create an instance of {@link com.redn.connect.vo.ResponseBody }
     * 
     */
    public com.redn.connect.vo.ResponseBody createResponseBody() {
        return new com.redn.connect.vo.ResponseBody();
    }

    /**
     * Create an instance of {@link ResponseHeader.Exception }
     * 
     */
    public ResponseHeader.Exception createResponseHeaderException() {
        return new ResponseHeader.Exception();
    }

    /**
     * Create an instance of {@link ConnectEnterpriseResponse.ResponseBody }
     * 
     */
    public ConnectEnterpriseResponse.ResponseBody createConnectEnterpriseResponseResponseBody() {
        return new ConnectEnterpriseResponse.ResponseBody();
    }

    /**
     * Create an instance of {@link ConnectEnterpriseMessage.EnterpriseBody }
     * 
     */
    public ConnectEnterpriseMessage.EnterpriseBody createConnectEnterpriseMessageEnterpriseBody() {
        return new ConnectEnterpriseMessage.EnterpriseBody();
    }

    /**
     * Create an instance of {@link EnterpriseHeader.Custom }
     * 
     */
    public EnterpriseHeader.Custom createEnterpriseHeaderCustom() {
        return new EnterpriseHeader.Custom();
    }

    /**
     * Create an instance of {@link EnterpriseHeader.Control }
     * 
     */
    public EnterpriseHeader.Control createEnterpriseHeaderControl() {
        return new EnterpriseHeader.Control();
    }

    /**
     * Create an instance of {@link ConnectEnterpriseException.OriginalMessage }
     * 
     */
    public ConnectEnterpriseException.OriginalMessage createConnectEnterpriseExceptionOriginalMessage() {
        return new ConnectEnterpriseException.OriginalMessage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnterpriseHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.connect.com/enterprise/services/2014/05", name = "EnterpriseHeader")
    public JAXBElement<EnterpriseHeader> createEnterpriseHeader(EnterpriseHeader value) {
        return new JAXBElement<EnterpriseHeader>(_EnterpriseHeader_QNAME, EnterpriseHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectEnterpriseResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.connect.com/enterprise/services/2014/05", name = "ConnectEnterpriseResponse")
    public JAXBElement<ConnectEnterpriseResponse> createConnectEnterpriseResponse(ConnectEnterpriseResponse value) {
        return new JAXBElement<ConnectEnterpriseResponse>(_ConnectEnterpriseResponse_QNAME, ConnectEnterpriseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectEnterpriseMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.connect.com/enterprise/services/2014/05", name = "ConnectEnterpriseMessage")
    public JAXBElement<ConnectEnterpriseMessage> createConnectEnterpriseMessage(ConnectEnterpriseMessage value) {
        return new JAXBElement<ConnectEnterpriseMessage>(_ConnectEnterpriseMessage_QNAME, ConnectEnterpriseMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectEnterpriseException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.connect.com/enterprise/services/2016/11", name = "ConnectEnterpriseException")
    public JAXBElement<ConnectEnterpriseException> createConnectEnterpriseException(ConnectEnterpriseException value) {
        return new JAXBElement<ConnectEnterpriseException>(_ConnectEnterpriseException_QNAME, ConnectEnterpriseException.class, null, value);
    }

}
