//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 02:38:11 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.connect.com/enterprise/services/2014/05", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.redn.connect.vo;
