//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 12:43:20 PM IST 
//


package com.redn.connect.zord05;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.redn.connect.zord05 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.redn.connect.zord05
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZORD05RED }
     * 
     */
    public ZORD05RED createZORD05RED() {
        return new ZORD05RED();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC }
     * 
     */
    public ZORD05RED.IDOC createZORD05REDIDOC() {
        return new ZORD05RED.IDOC();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDL37 }
     * 
     */
    public ZORD05RED.IDOC.E1EDL37 createZORD05REDIDOCE1EDL37() {
        return new ZORD05RED.IDOC.E1EDL37();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1CUCFG }
     * 
     */
    public ZORD05RED.IDOC.E1CUCFG createZORD05REDIDOCE1CUCFG() {
        return new ZORD05RED.IDOC.E1CUCFG();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 createZORD05REDIDOCE1EDP01() {
        return new ZORD05RED.IDOC.E1EDP01();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 createZORD05REDIDOCE1EDP01E1EDC01() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDCT1 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDCT1 createZORD05REDIDOCE1EDP01E1EDC01E1EDCT1() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDCT1();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDPT1 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDPT1 createZORD05REDIDOCE1EDP01E1EDPT1() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDPT1();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDPAD }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDPAD createZORD05REDIDOCE1EDP01E1EDPAD() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDPAD();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDPAD.E1TXTH1 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDPAD.E1TXTH1 createZORD05REDIDOCE1EDP01E1EDPADE1TXTH1() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDPAD.E1TXTH1();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDPA1 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDPA1 createZORD05REDIDOCE1EDP01E1EDPA1() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDPA1();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP05 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP05 createZORD05REDIDOCE1EDP01E1EDP05() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP05();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDKT1 }
     * 
     */
    public ZORD05RED.IDOC.E1EDKT1 createZORD05REDIDOCE1EDKT1() {
        return new ZORD05RED.IDOC.E1EDKT1();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDKA1 }
     * 
     */
    public ZORD05RED.IDOC.E1EDKA1 createZORD05REDIDOCE1EDKA1() {
        return new ZORD05RED.IDOC.E1EDKA1();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK01 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK01 createZORD05REDIDOCE1EDK01() {
        return new ZORD05RED.IDOC.E1EDK01();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.EDIDC40 }
     * 
     */
    public ZORD05RED.IDOC.EDIDC40 createZORD05REDIDOCEDIDC40() {
        return new ZORD05RED.IDOC.EDIDC40();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK14 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK14 createZORD05REDIDOCE1EDK14() {
        return new ZORD05RED.IDOC.E1EDK14();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK03 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK03 createZORD05REDIDOCE1EDK03() {
        return new ZORD05RED.IDOC.E1EDK03();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK04 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK04 createZORD05REDIDOCE1EDK04() {
        return new ZORD05RED.IDOC.E1EDK04();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK05 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK05 createZORD05REDIDOCE1EDK05() {
        return new ZORD05RED.IDOC.E1EDK05();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK02 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK02 createZORD05REDIDOCE1EDK02() {
        return new ZORD05RED.IDOC.E1EDK02();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK17 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK17 createZORD05REDIDOCE1EDK17() {
        return new ZORD05RED.IDOC.E1EDK17();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK18 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK18 createZORD05REDIDOCE1EDK18() {
        return new ZORD05RED.IDOC.E1EDK18();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK35 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK35 createZORD05REDIDOCE1EDK35() {
        return new ZORD05RED.IDOC.E1EDK35();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK36 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK36 createZORD05REDIDOCE1EDK36() {
        return new ZORD05RED.IDOC.E1EDK36();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDS01 }
     * 
     */
    public ZORD05RED.IDOC.E1EDS01 createZORD05REDIDOCE1EDS01() {
        return new ZORD05RED.IDOC.E1EDS01();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDL37 .E1EDL39 }
     * 
     */
    public ZORD05RED.IDOC.E1EDL37 .E1EDL39 createZORD05REDIDOCE1EDL37E1EDL39() {
        return new ZORD05RED.IDOC.E1EDL37 .E1EDL39();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDL37 .E1EDL38 }
     * 
     */
    public ZORD05RED.IDOC.E1EDL37 .E1EDL38 createZORD05REDIDOCE1EDL37E1EDL38() {
        return new ZORD05RED.IDOC.E1EDL37 .E1EDL38();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDL37 .E1EDL44 }
     * 
     */
    public ZORD05RED.IDOC.E1EDL37 .E1EDL44 createZORD05REDIDOCE1EDL37E1EDL44() {
        return new ZORD05RED.IDOC.E1EDL37 .E1EDL44();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1CUCFG.E1CUINS }
     * 
     */
    public ZORD05RED.IDOC.E1CUCFG.E1CUINS createZORD05REDIDOCE1CUCFGE1CUINS() {
        return new ZORD05RED.IDOC.E1CUCFG.E1CUINS();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1CUCFG.E1CUPRT }
     * 
     */
    public ZORD05RED.IDOC.E1CUCFG.E1CUPRT createZORD05REDIDOCE1CUCFGE1CUPRT() {
        return new ZORD05RED.IDOC.E1CUCFG.E1CUPRT();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1CUCFG.E1CUVAL }
     * 
     */
    public ZORD05RED.IDOC.E1CUCFG.E1CUVAL createZORD05REDIDOCE1CUCFGE1CUVAL() {
        return new ZORD05RED.IDOC.E1CUCFG.E1CUVAL();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1CUCFG.E1CUBLB }
     * 
     */
    public ZORD05RED.IDOC.E1CUCFG.E1CUBLB createZORD05REDIDOCE1CUCFGE1CUBLB() {
        return new ZORD05RED.IDOC.E1CUCFG.E1CUBLB();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .ZE1EDPFT01 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .ZE1EDPFT01 createZORD05REDIDOCE1EDP01ZE1EDPFT01() {
        return new ZORD05RED.IDOC.E1EDP01 .ZE1EDPFT01();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .ZE1EDP01 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .ZE1EDP01 createZORD05REDIDOCE1EDP01ZE1EDP01() {
        return new ZORD05RED.IDOC.E1EDP01 .ZE1EDP01();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP02 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP02 createZORD05REDIDOCE1EDP01E1EDP02() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP02();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1CUREF }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1CUREF createZORD05REDIDOCE1EDP01E1CUREF() {
        return new ZORD05RED.IDOC.E1EDP01 .E1CUREF();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1ADDI1 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1ADDI1 createZORD05REDIDOCE1EDP01E1ADDI1() {
        return new ZORD05RED.IDOC.E1EDP01 .E1ADDI1();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP03 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP03 createZORD05REDIDOCE1EDP01E1EDP03() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP03();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP04 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP04 createZORD05REDIDOCE1EDP01E1EDP04() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP04();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP20 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP20 createZORD05REDIDOCE1EDP01E1EDP20() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP20();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP19 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP19 createZORD05REDIDOCE1EDP01E1EDP19() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP19();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP17 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP17 createZORD05REDIDOCE1EDP01E1EDP17() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP17();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP18 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP18 createZORD05REDIDOCE1EDP01E1EDP18() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP18();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP35 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP35 createZORD05REDIDOCE1EDP01E1EDP35() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP35();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC02 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC02 createZORD05REDIDOCE1EDP01E1EDC01E1EDC02() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC02();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC03 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC03 createZORD05REDIDOCE1EDP01E1EDC01E1EDC03() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC03();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC04 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC04 createZORD05REDIDOCE1EDP01E1EDC01E1EDC04() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC04();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC05 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC05 createZORD05REDIDOCE1EDP01E1EDC01E1EDC05() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC05();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC06 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC06 createZORD05REDIDOCE1EDP01E1EDC01E1EDC06() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC06();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC07 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC07 createZORD05REDIDOCE1EDP01E1EDC01E1EDC07() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC07();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDCA1 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDCA1 createZORD05REDIDOCE1EDP01E1EDC01E1EDCA1() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDCA1();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC19 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC19 createZORD05REDIDOCE1EDP01E1EDC01E1EDC19() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC19();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC17 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC17 createZORD05REDIDOCE1EDP01E1EDC01E1EDC17() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC17();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC18 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC18 createZORD05REDIDOCE1EDP01E1EDC01E1EDC18() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDC18();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDCT1 .E1EDCT2 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDCT1 .E1EDCT2 createZORD05REDIDOCE1EDP01E1EDC01E1EDCT1E1EDCT2() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDC01 .E1EDCT1 .E1EDCT2();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDPT1 .E1EDPT2 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDPT1 .E1EDPT2 createZORD05REDIDOCE1EDP01E1EDPT1E1EDPT2() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDPT1 .E1EDPT2();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDPAD.E1TXTH1 .E1TXTP1 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDPAD.E1TXTH1 .E1TXTP1 createZORD05REDIDOCE1EDP01E1EDPADE1TXTH1E1TXTP1() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDPAD.E1TXTH1 .E1TXTP1();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDPA1 .E1EDPA3 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDPA1 .E1EDPA3 createZORD05REDIDOCE1EDP01E1EDPA1E1EDPA3() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDPA1 .E1EDPA3();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDP01 .E1EDP05 .E1EDPS5 }
     * 
     */
    public ZORD05RED.IDOC.E1EDP01 .E1EDP05 .E1EDPS5 createZORD05REDIDOCE1EDP01E1EDP05E1EDPS5() {
        return new ZORD05RED.IDOC.E1EDP01 .E1EDP05 .E1EDPS5();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDKT1 .E1EDKT2 }
     * 
     */
    public ZORD05RED.IDOC.E1EDKT1 .E1EDKT2 createZORD05REDIDOCE1EDKT1E1EDKT2() {
        return new ZORD05RED.IDOC.E1EDKT1 .E1EDKT2();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDKA1 .E1EDKA3 }
     * 
     */
    public ZORD05RED.IDOC.E1EDKA1 .E1EDKA3 createZORD05REDIDOCE1EDKA1E1EDKA3() {
        return new ZORD05RED.IDOC.E1EDKA1 .E1EDKA3();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK01 .ZE1EDKFT01 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK01 .ZE1EDKFT01 createZORD05REDIDOCE1EDK01ZE1EDKFT01() {
        return new ZORD05RED.IDOC.E1EDK01 .ZE1EDKFT01();
    }

    /**
     * Create an instance of {@link ZORD05RED.IDOC.E1EDK01 .ZE1EDK01 }
     * 
     */
    public ZORD05RED.IDOC.E1EDK01 .ZE1EDK01 createZORD05REDIDOCE1EDK01ZE1EDK01() {
        return new ZORD05RED.IDOC.E1EDK01 .ZE1EDK01();
    }

}
