//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.12 at 12:51:51 PM IST 
//


package com.redn.connect.ZINV02;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZINV02RED }
     * 
     */
    public ZINV02RED createZINV02RED() {
        return new ZINV02RED();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC }
     * 
     */
    public ZINV02RED.IDOC createZINV02REDIDOC() {
        return new ZINV02RED.IDOC();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 createZINV02REDIDOCE1EDP01() {
        return new ZINV02RED.IDOC.E1EDP01();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDPT1 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDPT1 createZINV02REDIDOCE1EDP01E1EDPT1() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDPT1();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDKT1 }
     * 
     */
    public ZINV02RED.IDOC.E1EDKT1 createZINV02REDIDOCE1EDKT1() {
        return new ZINV02RED.IDOC.E1EDKT1();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK01 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK01 createZINV02REDIDOCE1EDK01() {
        return new ZINV02RED.IDOC.E1EDK01();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.EDIDC40 }
     * 
     */
    public ZINV02RED.IDOC.EDIDC40 createZINV02REDIDOCEDIDC40() {
        return new ZINV02RED.IDOC.EDIDC40();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDKA1 }
     * 
     */
    public ZINV02RED.IDOC.E1EDKA1 createZINV02REDIDOCE1EDKA1() {
        return new ZINV02RED.IDOC.E1EDKA1();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK02 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK02 createZINV02REDIDOCE1EDK02() {
        return new ZINV02RED.IDOC.E1EDK02();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK03 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK03 createZINV02REDIDOCE1EDK03() {
        return new ZINV02RED.IDOC.E1EDK03();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK05 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK05 createZINV02REDIDOCE1EDK05() {
        return new ZINV02RED.IDOC.E1EDK05();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK04 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK04 createZINV02REDIDOCE1EDK04() {
        return new ZINV02RED.IDOC.E1EDK04();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK17 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK17 createZINV02REDIDOCE1EDK17() {
        return new ZINV02RED.IDOC.E1EDK17();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK18 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK18 createZINV02REDIDOCE1EDK18() {
        return new ZINV02RED.IDOC.E1EDK18();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK23 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK23 createZINV02REDIDOCE1EDK23() {
        return new ZINV02RED.IDOC.E1EDK23();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK28 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK28 createZINV02REDIDOCE1EDK28() {
        return new ZINV02RED.IDOC.E1EDK28();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK29 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK29 createZINV02REDIDOCE1EDK29() {
        return new ZINV02RED.IDOC.E1EDK29();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK14 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK14 createZINV02REDIDOCE1EDK14() {
        return new ZINV02RED.IDOC.E1EDK14();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDS01 }
     * 
     */
    public ZINV02RED.IDOC.E1EDS01 createZINV02REDIDOCE1EDS01() {
        return new ZINV02RED.IDOC.E1EDS01();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .ZE1EDPFT01 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .ZE1EDPFT01 createZINV02REDIDOCE1EDP01ZE1EDPFT01() {
        return new ZINV02RED.IDOC.E1EDP01 .ZE1EDPFT01();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .ZE1EDP01 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .ZE1EDP01 createZINV02REDIDOCE1EDP01ZE1EDP01() {
        return new ZINV02RED.IDOC.E1EDP01 .ZE1EDP01();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDP02 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDP02 createZINV02REDIDOCE1EDP01E1EDP02() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDP02();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDP03 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDP03 createZINV02REDIDOCE1EDP01E1EDP03() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDP03();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDP19 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDP19 createZINV02REDIDOCE1EDP01E1EDP19() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDP19();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDP26 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDP26 createZINV02REDIDOCE1EDP01E1EDP26() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDP26();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDPA1 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDPA1 createZINV02REDIDOCE1EDP01E1EDPA1() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDPA1();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDP05 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDP05 createZINV02REDIDOCE1EDP01E1EDP05() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDP05();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDP04 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDP04 createZINV02REDIDOCE1EDP01E1EDP04() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDP04();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDP28 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDP28 createZINV02REDIDOCE1EDP01E1EDP28() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDP28();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDP08 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDP08 createZINV02REDIDOCE1EDP01E1EDP08() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDP08();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDP30 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDP30 createZINV02REDIDOCE1EDP01E1EDP30() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDP30();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDP01 .E1EDPT1 .E1EDPT2 }
     * 
     */
    public ZINV02RED.IDOC.E1EDP01 .E1EDPT1 .E1EDPT2 createZINV02REDIDOCE1EDP01E1EDPT1E1EDPT2() {
        return new ZINV02RED.IDOC.E1EDP01 .E1EDPT1 .E1EDPT2();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDKT1 .E1EDKT2 }
     * 
     */
    public ZINV02RED.IDOC.E1EDKT1 .E1EDKT2 createZINV02REDIDOCE1EDKT1E1EDKT2() {
        return new ZINV02RED.IDOC.E1EDKT1 .E1EDKT2();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK01 .ZE1EDKFT01 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK01 .ZE1EDKFT01 createZINV02REDIDOCE1EDK01ZE1EDKFT01() {
        return new ZINV02RED.IDOC.E1EDK01 .ZE1EDKFT01();
    }

    /**
     * Create an instance of {@link ZINV02RED.IDOC.E1EDK01 .ZE1EDK01 }
     * 
     */
    public ZINV02RED.IDOC.E1EDK01 .ZE1EDK01 createZINV02REDIDOCE1EDK01ZE1EDK01() {
        return new ZINV02RED.IDOC.E1EDK01 .ZE1EDK01();
    }

}
